force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Name of the Apex Class from where the logging event was fired.</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PlatformEventLog.cls
/**
 * @description
 */
public with sharing class PlatformEventLog extends LoggerBase {
    protected override void commitLogs() {
        List<LogEvent__e> events = new List<LogEvent__e>();

        for (SingleLog log : logs) {
            events.add(new LogEvent__e(
                    ApexClass__c = log.ApexClass,
                    LoggingLevel__c = log.Level.name().toLowerCase().capitalize(),
                    Body__c = log.Message,
                    UserId__c = UserInfo.getUserId()
            ));
        }

        EventBus.publish(events);
    }
}